package view;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.CentralDeIdeias;
import model.GerenciadorArquivos;
import static model.CentralDeIdeias.arrayDeIdeia;

/**
 * Classe responsavel pela parte visual de alteração, exclusão de ideias, sendo
 * que a mesma é utlizada nos menus de alterar ideia e deletar ideia,isto
 * acontece atravez do parametro contendo uma busca por palavras que estiverem
 * na ideia cadastrada e escolhe na tabela qual será deletada clique deleta pelo
 * codigo
 *
 * @author Huilton
 * @version 1.0
 */
public class FrmiAlterarIdeia extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmiAlterarIdeia
     */
    public FrmiAlterarIdeia() {
        initComponents();
        inserirTodosFuncionarioaNaTabela();
        jlpAlteracao.setVisible(false);
        for (int i = 0; i < arrayDeIdeia.size(); i++) {
            if (Menu.senhaLoginAux.equals(arrayDeIdeia.get(i).getSenha())
                    && Menu.nomeLoginAux.equals(arrayDeIdeia.get(i).getAuxFunconario())) {
                txtPontuacaoTotal.setText("" + c.contagenDePontos(Menu.nomeLoginAux, Menu.senhaLoginAux));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        jlpAlteracao = new javax.swing.JLayeredPane();
        btnCancelar = new javax.swing.JButton();
        btnSalvarAlteracoes = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNodeIdeia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtIdeiaFuncionario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFuncionario = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtPontuacaoTotal = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtIdeiaFuncionarioTabela = new javax.swing.JTextPane();
        btnDeletar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setTitle("Banco de Idéias Interdisciplinar Qi");
        setPreferredSize(new java.awt.Dimension(900, 540));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alteração e Exclusão de Idéias", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Pesquisa:");

        txtPesquisa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        btnBuscar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones32/Pesquisar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAtualizar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones32/Devolução.png"))); // NOI18N
        btnAtualizar.setText("Atualizar");
        btnAtualizar.setPreferredSize(new java.awt.Dimension(119, 28));
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        jlpAlteracao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Manutenção de alteração", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Arial", 0, 12))); // NOI18N
        jlpAlteracao.setAutoscrolls(true);

        btnCancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones32/Cancel-32.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setPreferredSize(new java.awt.Dimension(90, 28));
        btnCancelar.setRequestFocusEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        btnCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCancelarKeyPressed(evt);
            }
        });
        jlpAlteracao.add(btnCancelar);
        btnCancelar.setBounds(420, 180, 170, 30);

        btnSalvarAlteracoes.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSalvarAlteracoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones32/Salvar.png"))); // NOI18N
        btnSalvarAlteracoes.setText("Salvar Alterações");
        btnSalvarAlteracoes.setPreferredSize(new java.awt.Dimension(90, 28));
        btnSalvarAlteracoes.setRequestFocusEnabled(false);
        btnSalvarAlteracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarAlteracoesActionPerformed(evt);
            }
        });
        btnSalvarAlteracoes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSalvarAlteracoesKeyPressed(evt);
            }
        });
        jlpAlteracao.add(btnSalvarAlteracoes);
        btnSalvarAlteracoes.setBounds(180, 180, 190, 30);

        txtCodigo.setEditable(false);
        txtCodigo.setBackground(new java.awt.Color(204, 204, 204));
        txtCodigo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlpAlteracao.add(txtCodigo);
        txtCodigo.setBounds(180, 50, 52, 28);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Codigo");
        jlpAlteracao.add(jLabel2);
        jLabel2.setBounds(110, 60, 50, 15);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Nome da Idéia");
        jlpAlteracao.add(jLabel3);
        jLabel3.setBounds(80, 100, 81, 15);

        txtNodeIdeia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlpAlteracao.add(txtNodeIdeia);
        txtNodeIdeia.setBounds(180, 90, 530, 28);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Idéia");
        jlpAlteracao.add(jLabel4);
        jLabel4.setBounds(130, 140, 27, 15);

        txtIdeiaFuncionario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlpAlteracao.add(txtIdeiaFuncionario);
        txtIdeiaFuncionario.setBounds(180, 130, 530, 28);

        tblFuncionario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código da idéia", "Usuário", "Nome da Idéia", "Pontos por idéia", "Senha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFuncionario.setToolTipText("Selecione uma linha para Alterar");
        tblFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFuncionarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblFuncionario);
        if (tblFuncionario.getColumnModel().getColumnCount() > 0) {
            tblFuncionario.getColumnModel().getColumn(4).setMinWidth(0);
            tblFuncionario.getColumnModel().getColumn(4).setPreferredWidth(0);
            tblFuncionario.getColumnModel().getColumn(4).setMaxWidth(0);
        }

        txtPontuacaoTotal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total De Pontos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 12))); // NOI18N
        txtPontuacaoTotal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtPontuacaoTotal.setPreferredSize(new java.awt.Dimension(10, 43));
        jScrollPane3.setViewportView(txtPontuacaoTotal);

        txtIdeiaFuncionarioTabela.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Idéia ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 12))); // NOI18N
        txtIdeiaFuncionarioTabela.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jScrollPane2.setViewportView(txtIdeiaFuncionarioTabela);

        btnDeletar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones32/Delete-32.png"))); // NOI18N
        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlpAlteracao)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDeletar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 109, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jlpAlteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    DefaultTableModel dtm;
    int linhaSelecionada = 0;
    CentralDeIdeias c = new CentralDeIdeias();

    public void limpar() {
        txtCodigo.setText("");
        txtIdeiaFuncionario.setText("");
        txtNodeIdeia.setText("");
        txtPesquisa.setText("");
        txtIdeiaFuncionarioTabela.setText("");
        txtPontuacaoTotal.setText("");
    }

    private void salvar() {
        try {
            for (int i = 0; i < arrayDeIdeia.size(); i++) {
                if (arrayDeIdeia.get(i).getNomeIdeia().equals(txtNodeIdeia.getText())
                        && arrayDeIdeia.get(i).getCodigo() != Integer.parseInt(txtCodigo.getText())) {
                    throw new Exception("\n Nome da Idéia já cadastrada!");
                } else if (arrayDeIdeia.get(i).getIdeiaFuncionario().equals(txtIdeiaFuncionario.getText())
                        && arrayDeIdeia.get(i).getCodigo() != Integer.parseInt(txtCodigo.getText())) {
                    throw new Exception("\n Idéia já cadastrada!");
                } else if (arrayDeIdeia.get(i).getSenha().equals(Menu.senhaLoginAux) && arrayDeIdeia.get(i).getCodigo() == Integer.parseInt(txtCodigo.getText())) {
                    arrayDeIdeia.get(i).setCodigo(Integer.parseInt(txtCodigo.getText()));
                    arrayDeIdeia.get(i).setNomeIdeia(txtNodeIdeia.getText());
                    arrayDeIdeia.get(i).setIdeiaFuncionario(txtIdeiaFuncionario.getText());
                    arrayDeIdeia.get(i).getPontos();
                    arrayDeIdeia.get(i).getSenha();
                    arrayDeIdeia.get(i).getAuxFunconario();

                    JOptionPane.showMessageDialog(this, "Aletração efetuada com sucesso!!", "Informativo", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            GerenciadorArquivos.salvarEAlterarIdeia();
            txtPesquisa.setText(txtNodeIdeia.getText());
            buscar();
            limpar();
            jlpAlteracao.setVisible(false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), " ERRO ", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }

    private void inserirTodosFuncionarioaNaTabela() {
        GerenciadorArquivos.buscarArquivosIdeia();
        try {

            DefaultTableModel dtm = (DefaultTableModel) tblFuncionario.getModel();

            String[] linha = new String[5];

            dtm.setNumRows(0);
            for (int i = 0; i < arrayDeIdeia.size(); i++) {
                if (arrayDeIdeia.get(i).getSenha().equals(Menu.senhaLoginAux)
                        && arrayDeIdeia.get(i).getAuxFunconario().equals(Menu.nomeLoginAux)) {
                    linha[0] = String.valueOf(arrayDeIdeia.get(i).getCodigo());
                    linha[1] = arrayDeIdeia.get(i).getAuxFunconario();
                    linha[2] = arrayDeIdeia.get(i).getNomeIdeia();
                    linha[3] = String.valueOf(arrayDeIdeia.get(i).getPontos());
                    linha[4] = arrayDeIdeia.get(i).getSenha();
                    txtIdeiaFuncionarioTabela.setText(arrayDeIdeia.get(i).getIdeiaFuncionario());
                    dtm.addRow(linha);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), " ERRO ", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void buscar() {

        if (txtPesquisa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, " Infome um campo para pesquisa por favor!! ", " !! ALERTA !!", JOptionPane.INFORMATION_MESSAGE);
            txtPesquisa.requestFocus();

        } else {

            String auxPesquisa = txtPesquisa.getText();

            dtm = (DefaultTableModel) tblFuncionario.getModel();
            dtm.setNumRows(0);
            String[] linha = new String[5];
            for (int i = 0; i < arrayDeIdeia.size(); i++) {
                if (arrayDeIdeia.get(i).getSenha().equals(Menu.senhaLoginAux)
                        && arrayDeIdeia.get(i).getNomeIdeia().equals(auxPesquisa)) {

                    linha[0] = String.valueOf(arrayDeIdeia.get(i).getCodigo());
                    linha[1] = arrayDeIdeia.get(i).getAuxFunconario();
                    linha[2] = arrayDeIdeia.get(i).getNomeIdeia();
                    linha[3] = String.valueOf(arrayDeIdeia.get(i).getPontos());
                    linha[4] = arrayDeIdeia.get(i).getSenha();

                    txtIdeiaFuncionarioTabela.setText(arrayDeIdeia.get(i).getIdeiaFuncionario());
                    dtm.addRow(linha);
                    txtCodigo.setText("" + arrayDeIdeia.get(i).getCodigo());
                    txtNodeIdeia.setText(arrayDeIdeia.get(i).getNomeIdeia());
                    txtIdeiaFuncionario.setText(arrayDeIdeia.get(i).getIdeiaFuncionario());
                }
            }
            if (dtm.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Idéia Não Encontrada", " !! ERRO !! ", JOptionPane.ERROR_MESSAGE);
                txtIdeiaFuncionarioTabela.setText("");
            }

        }
    }
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscar();

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        GerenciadorArquivos.buscarArquivosIdeia();
        inserirTodosFuncionarioaNaTabela();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        limpar();
        txtPesquisa.requestFocus();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCancelarKeyPressed
        try {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                limpar();
                txtPesquisa.requestFocus();
            } else if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
                limpar();
                txtPesquisa.requestFocus();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), " !! ERRO !! ", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnCancelarKeyPressed

    private void btnSalvarAlteracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAlteracoesActionPerformed
        try {
            salvar();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), " !! ERRO !! ", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnSalvarAlteracoesActionPerformed

    private void btnSalvarAlteracoesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSalvarAlteracoesKeyPressed

        try {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                salvar();
            } else if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
                salvar();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), " !! ERRO !! ", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarAlteracoesKeyPressed

    private void tblFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFuncionarioMouseClicked
        jlpAlteracao.setVisible(true);
        linhaSelecionada = tblFuncionario.getSelectedRow();
        txtPesquisa.setText((String) tblFuncionario.getValueAt(linhaSelecionada, 2).toString());
        String nome = (String) tblFuncionario.getValueAt(linhaSelecionada, 1).toString();
        String senha = (String) tblFuncionario.getValueAt(linhaSelecionada, 4).toString();
        buscar();
        txtPontuacaoTotal.setText("" + c.contagenDePontos(nome, senha));
    }//GEN-LAST:event_tblFuncionarioMouseClicked

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        GerenciadorArquivos.buscarArquivosIdeia();

        if (!txtNodeIdeia.getText().equals("")) {

            int aux = JOptionPane.showConfirmDialog(this, " Tem certeza de que deseja excluir esta idéia? ",
                    "Exlcuir idéia", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

            if (JOptionPane.YES_OPTION == aux) {

                for (int i = 0; i < arrayDeIdeia.size(); i++) {
                    if (!txtNodeIdeia.getText().equals("")
                            && Menu.senhaLoginAux.equals(arrayDeIdeia.get(i).getSenha())
                            && arrayDeIdeia.get(i).getNomeIdeia().equals(txtNodeIdeia.getText())) {
                        GerenciadorArquivos.deletarArquivoIdeia(arrayDeIdeia.get(i).getNomeIdeia());
                        JOptionPane.showMessageDialog(this, "Idéia Excluída com sucesso", "Exclusão de idéia", JOptionPane.INFORMATION_MESSAGE);
                        GerenciadorArquivos.buscarArquivosIdeia();
                        inserirTodosFuncionarioaNaTabela();
                        limpar();

                    }
                }
                int quantidadeRegistro = tblFuncionario.getRowCount();
                if (quantidadeRegistro > linhaSelecionada) {
                    tblFuncionario.setRowSelectionInterval(linhaSelecionada, linhaSelecionada);
                } else if (tblFuncionario.getRowCount() > 0) {
                    tblFuncionario.setRowSelectionInterval(linhaSelecionada - 1, linhaSelecionada - 1);
                }
            } else {
                inserirTodosFuncionarioaNaTabela();
                txtPesquisa.requestFocus();
                aux = 2;
                dispose();

            }
        }
    }//GEN-LAST:event_btnDeletarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnSalvarAlteracoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLayeredPane jlpAlteracao;
    private javax.swing.JTable tblFuncionario;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtIdeiaFuncionario;
    private javax.swing.JTextPane txtIdeiaFuncionarioTabela;
    private javax.swing.JTextField txtNodeIdeia;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextPane txtPontuacaoTotal;
    // End of variables declaration//GEN-END:variables
}
