/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.CentralDeIdeias;
import static model.CentralDeIdeias.arrayDeIdeia;
import model.GerenciadorArquivos;

/**
 *
 * @author Binho
 */
public class FrmManutençãoDeIdeias extends javax.swing.JInternalFrame {

    /**
     * Creates new form GuiCadastrarFuncionario
     */
    public FrmManutençãoDeIdeias() {
        initComponents();
        inserirTodosFuncionariosNaTabela();
        jlpAlteracao.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane3 = new javax.swing.JLayeredPane();
        jlpAlteracao = new javax.swing.JLayeredPane();
        btnCancelar = new javax.swing.JButton();
        btnSalvarAlteracoes = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNomeIdeia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtIdeiaFuncionario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFuncionario = new javax.swing.JTable();
        txtPesquisa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtIdeiaFuncionarioTabela = new javax.swing.JTextPane();
        btnAtualizar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtPontuacaoTotal = new javax.swing.JTextPane();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Banco de Idéias Interdisciplinar Qi");
        setAutoscrolls(true);
        setFocusable(false);
        setMinimumSize(new java.awt.Dimension(25, 33));
        setPreferredSize(new java.awt.Dimension(900, 588));

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabela De Manutenção de Idéias", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jLayeredPane3.setPreferredSize(new java.awt.Dimension(806, 550));

        jlpAlteracao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Manutenção De Correntistas E Administradores", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Arial", 1, 12))); // NOI18N
        jlpAlteracao.setAutoscrolls(true);

        btnCancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones32/Cancel-32.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setPreferredSize(new java.awt.Dimension(90, 28));
        btnCancelar.setRequestFocusEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        btnCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCancelarKeyPressed(evt);
            }
        });
        jlpAlteracao.add(btnCancelar);
        btnCancelar.setBounds(420, 180, 170, 30);

        btnSalvarAlteracoes.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSalvarAlteracoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones32/Salvar.png"))); // NOI18N
        btnSalvarAlteracoes.setText("Salvar Alterações");
        btnSalvarAlteracoes.setPreferredSize(new java.awt.Dimension(90, 28));
        btnSalvarAlteracoes.setRequestFocusEnabled(false);
        btnSalvarAlteracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarAlteracoesActionPerformed(evt);
            }
        });
        btnSalvarAlteracoes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSalvarAlteracoesKeyPressed(evt);
            }
        });
        jlpAlteracao.add(btnSalvarAlteracoes);
        btnSalvarAlteracoes.setBounds(180, 180, 190, 30);

        txtCodigo.setEditable(false);
        txtCodigo.setBackground(new java.awt.Color(204, 204, 204));
        txtCodigo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlpAlteracao.add(txtCodigo);
        txtCodigo.setBounds(180, 50, 52, 28);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Codigo");
        jlpAlteracao.add(jLabel2);
        jLabel2.setBounds(110, 60, 50, 15);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Nome da Idéia");
        jlpAlteracao.add(jLabel3);
        jLabel3.setBounds(80, 100, 81, 15);

        txtNomeIdeia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlpAlteracao.add(txtNomeIdeia);
        txtNomeIdeia.setBounds(180, 90, 594, 28);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Idéia");
        jlpAlteracao.add(jLabel4);
        jLabel4.setBounds(130, 140, 27, 15);

        txtIdeiaFuncionario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlpAlteracao.add(txtIdeiaFuncionario);
        txtIdeiaFuncionario.setBounds(180, 130, 594, 28);

        tblFuncionario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código da idéia", "Usuário", "Nome da Idéia", "Pontos por idéia", "Senha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFuncionario.setToolTipText("Selecione uma linha para Alterar");
        tblFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFuncionarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblFuncionario);
        if (tblFuncionario.getColumnModel().getColumnCount() > 0) {
            tblFuncionario.getColumnModel().getColumn(0).setMinWidth(120);
            tblFuncionario.getColumnModel().getColumn(0).setPreferredWidth(120);
            tblFuncionario.getColumnModel().getColumn(0).setMaxWidth(120);
            tblFuncionario.getColumnModel().getColumn(1).setResizable(false);
            tblFuncionario.getColumnModel().getColumn(3).setMinWidth(120);
            tblFuncionario.getColumnModel().getColumn(3).setPreferredWidth(120);
            tblFuncionario.getColumnModel().getColumn(3).setMaxWidth(120);
            tblFuncionario.getColumnModel().getColumn(4).setMinWidth(0);
            tblFuncionario.getColumnModel().getColumn(4).setPreferredWidth(0);
            tblFuncionario.getColumnModel().getColumn(4).setMaxWidth(0);
        }

        txtPesquisa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtPesquisa.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Pesquisa:");

        btnBuscar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones32/Pesquisar.png"))); // NOI18N
        btnBuscar.setText("Pesquisar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtIdeiaFuncionarioTabela.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Idéia ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 12))); // NOI18N
        txtIdeiaFuncionarioTabela.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jScrollPane2.setViewportView(txtIdeiaFuncionarioTabela);

        btnAtualizar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones32/Devolução.png"))); // NOI18N
        btnAtualizar.setText("Atualizar");
        btnAtualizar.setPreferredSize(new java.awt.Dimension(119, 28));
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnDeletar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones32/Delete-32.png"))); // NOI18N
        btnDeletar.setText("Deletar");
        btnDeletar.setToolTipText("Selecione uma Linha Na Tabela");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        txtPontuacaoTotal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total De Pontos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 12))); // NOI18N
        txtPontuacaoTotal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtPontuacaoTotal.setPreferredSize(new java.awt.Dimension(10, 43));
        jScrollPane3.setViewportView(txtPontuacaoTotal);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlpAlteracao)
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(347, 347, 347)))
                .addContainerGap())
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 113, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jlpAlteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jLayeredPane3.setLayer(jlpAlteracao, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jlpAlteracao.getAccessibleContext().setAccessibleName("Manutenção RH");
        jLayeredPane3.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(txtPesquisa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(btnBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(btnAtualizar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(btnDeletar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 873, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    DefaultTableModel dtm;
    Integer linhaSelecionada = 0;
    CentralDeIdeias c = new CentralDeIdeias();

    public void limpar() {
        txtCodigo.setText("");
        txtIdeiaFuncionario.setText("");
        txtNomeIdeia.setText("");
        txtPesquisa.setText("");
        txtIdeiaFuncionarioTabela.setText("");
        txtPontuacaoTotal.setText("");

    }

    private void salvar() {
        try {
            for (int i = 0; i < arrayDeIdeia.size(); i++) {
                if (arrayDeIdeia.get(i).getNomeIdeia().equals(txtNomeIdeia.getText())
                        && arrayDeIdeia.get(i).getCodigo() != Integer.parseInt(txtCodigo.getText())) {
                    throw new Exception("\n Nome da Idéia já cadastrada!");
                } else if (arrayDeIdeia.get(i).getIdeiaFuncionario().equals(txtIdeiaFuncionario.getText())
                        && arrayDeIdeia.get(i).getCodigo() != Integer.parseInt(txtCodigo.getText())) {
                    throw new Exception("\n Idéia já cadastrada!");
                } else if (arrayDeIdeia.get(i).getSenha().equals(Menu.senhaLoginAux) && arrayDeIdeia.get(i).getCodigo() == Integer.parseInt(txtCodigo.getText())) {

                    arrayDeIdeia.get(i).setCodigo(Integer.parseInt(txtCodigo.getText()));
                    arrayDeIdeia.get(i).setNomeIdeia(txtNomeIdeia.getText());
                    arrayDeIdeia.get(i).setIdeiaFuncionario(txtIdeiaFuncionario.getText());
                    arrayDeIdeia.get(i).getPontos();
                    arrayDeIdeia.get(i).getSenha();
                    arrayDeIdeia.get(i).getAuxFunconario();

                    JOptionPane.showMessageDialog(this, "Aletração efetuada com sucesso!!", "Informativo", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            GerenciadorArquivos.salvarEAlterarIdeia();
            inserirTodosFuncionariosNaTabela();
            this.limpar();
            jlpAlteracao.setVisible(false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), " ERRO ", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }

    private void inserirTodosFuncionariosNaTabela() {
        GerenciadorArquivos.buscarArquivosIdeia();
        try {

            DefaultTableModel dtm = (DefaultTableModel) tblFuncionario.getModel();

            String[] linha = new String[5];

            dtm.setNumRows(0);

            for (int i = 0; i < arrayDeIdeia.size(); i++) {
                linha[0] = String.valueOf(arrayDeIdeia.get(i).getCodigo());
                linha[1] = arrayDeIdeia.get(i).getAuxFunconario();
                linha[2] = arrayDeIdeia.get(i).getNomeIdeia();
                linha[3] = String.valueOf(arrayDeIdeia.get(i).getPontos());
                linha[4] = arrayDeIdeia.get(i).getSenha();
                txtPontuacaoTotal.setText(""+c.contagenDePontos(Menu.nomeLoginAux, Menu.senhaLoginAux));
                txtIdeiaFuncionarioTabela.setText(arrayDeIdeia.get(i).getIdeiaFuncionario());
                dtm.addRow(linha);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), " ERRO ", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void buscar() {
        if (txtPesquisa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, " Infome um campo para pesquisa por favor!! ", " !! ALERTA !!", JOptionPane.INFORMATION_MESSAGE);
            txtPesquisa.requestFocus();

        } else {
            dtm = (DefaultTableModel) tblFuncionario.getModel();
            dtm.setNumRows(0);
            String[] linha = new String[5];
            for (int i = 0; i < arrayDeIdeia.size(); i++) {

                if (arrayDeIdeia.get(i).getNomeIdeia().equals(txtPesquisa.getText())) {

                    linha[0] = String.valueOf(arrayDeIdeia.get(i).getCodigo());
                    linha[1] = arrayDeIdeia.get(i).getAuxFunconario();
                    linha[2] = arrayDeIdeia.get(i).getNomeIdeia();
                    linha[3] = String.valueOf(arrayDeIdeia.get(i).getPontos());
                    linha[4] = arrayDeIdeia.get(i).getSenha();

                    txtIdeiaFuncionarioTabela.setText(arrayDeIdeia.get(i).getIdeiaFuncionario());

                    dtm.addRow(linha);
                    txtCodigo.setText("" + arrayDeIdeia.get(i).getCodigo());
                    txtNomeIdeia.setText(arrayDeIdeia.get(i).getNomeIdeia());
                    txtIdeiaFuncionario.setText(arrayDeIdeia.get(i).getIdeiaFuncionario());
                }
            }
            if (dtm.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Idéia Não Encontrada", " !! ERRO !! ", JOptionPane.ERROR_MESSAGE);
                txtIdeiaFuncionarioTabela.setText("");
            }

        }
    }


    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed

        jlpAlteracao.setVisible(false);
        GerenciadorArquivos.buscarArquivosIdeia();
        limpar();
        inserirTodosFuncionariosNaTabela();

    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tblFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFuncionarioMouseClicked
        jlpAlteracao.setVisible(true);
        linhaSelecionada = tblFuncionario.getSelectedRow();
        txtPesquisa.setText((String) tblFuncionario.getValueAt(linhaSelecionada, 2).toString());
        String nome = (String) tblFuncionario.getValueAt(linhaSelecionada, 1).toString();
        String senha = (String) tblFuncionario.getValueAt(linhaSelecionada, 4).toString();
        buscar();
        txtPontuacaoTotal.setText("" + c.contagenDePontos(nome, senha));
    }//GEN-LAST:event_tblFuncionarioMouseClicked

    private void btnSalvarAlteracoesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSalvarAlteracoesKeyPressed

        try {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                salvar();
            } else if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
                salvar();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), " ERRO ", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarAlteracoesKeyPressed

    private void btnSalvarAlteracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAlteracoesActionPerformed
        try {
            salvar();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "  ERRO  ", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnSalvarAlteracoesActionPerformed

    private void btnCancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCancelarKeyPressed
        try {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                limpar();
                txtPesquisa.requestFocus();
            } else if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
                limpar();
                txtPesquisa.requestFocus();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "  ERRO  ", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnCancelarKeyPressed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        limpar();
        txtPesquisa.requestFocus();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        GerenciadorArquivos.buscarArquivosIdeia();

        if (!txtNomeIdeia.getText().equals("")) {

            int aux = JOptionPane.showConfirmDialog(this, " Tem certeza de que deseja excluir esta idéia? ",
                    "Exlcuir idéia", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

            if (JOptionPane.YES_OPTION == aux) {

                for (int i = 0; i < arrayDeIdeia.size(); i++) {
                    if (!txtNomeIdeia.getText().equals("")
                            && arrayDeIdeia.get(i).getNomeIdeia().equals(txtNomeIdeia.getText())) {
                        GerenciadorArquivos.deletarArquivoIdeia(arrayDeIdeia.get(i).getNomeIdeia());
                        JOptionPane.showMessageDialog(this, "Excluído com sucesso", "Exclusão de idéia", JOptionPane.INFORMATION_MESSAGE);
                        GerenciadorArquivos.buscarArquivosIdeia();
                        inserirTodosFuncionariosNaTabela();
                       
                    }
                }
                int quantidadeRegistro = tblFuncionario.getRowCount();
                if (quantidadeRegistro > linhaSelecionada) {
                    tblFuncionario.setRowSelectionInterval(linhaSelecionada, linhaSelecionada);
                } else if (tblFuncionario.getRowCount() > 0) {
                    tblFuncionario.setRowSelectionInterval(linhaSelecionada - 1, linhaSelecionada - 1);
                }
            } else {
                inserirTodosFuncionariosNaTabela();
                txtPesquisa.requestFocus();
                aux = -1;
                dispose();

            }
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnSalvarAlteracoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLayeredPane jlpAlteracao;
    private javax.swing.JTable tblFuncionario;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtIdeiaFuncionario;
    private javax.swing.JTextPane txtIdeiaFuncionarioTabela;
    private javax.swing.JTextField txtNomeIdeia;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextPane txtPontuacaoTotal;
    // End of variables declaration//GEN-END:variables

}
