/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.CentralDeIdeias;
import static model.CentralDeIdeias.arrayDeIdeia;
import static model.CentralDeIdeias.arrayDeUsuarios;
import model.GerenciadorArquivos;

/**
 *
 * @author Binho
 */
public class FrmManutençãoDeUsuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form GuiCadastrarFuncionario
     */
    public FrmManutençãoDeUsuarios() {
        initComponents();
        inserirTodosFuncionariosNaTabela();
        jlpAlteracao.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane3 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFuncionario = new javax.swing.JTable();
        jbDeletar = new javax.swing.JButton();
        jbAtualizar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        txtPesquisa = new javax.swing.JTextField();
        jlpAlteracao = new javax.swing.JLayeredPane();
        btnCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        jcbNomeTipo = new javax.swing.JComboBox<String>();
        btnSalvarAlteracoes = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtConfirmacaoDeSenha = new javax.swing.JPasswordField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Banco de Idéias Interdisciplinar Qi");
        setAutoscrolls(true);
        setFocusable(false);
        setMinimumSize(new java.awt.Dimension(25, 33));

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabela De Manutenção de Usuários", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jLayeredPane3.setPreferredSize(new java.awt.Dimension(806, 550));

        tblFuncionario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tblFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Senha", "Tipo De Usuário"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFuncionario.setToolTipText("Selecione uma linha para Alterar");
        tblFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFuncionarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblFuncionario);
        if (tblFuncionario.getColumnModel().getColumnCount() > 0) {
            tblFuncionario.getColumnModel().getColumn(0).setResizable(false);
            tblFuncionario.getColumnModel().getColumn(1).setResizable(false);
            tblFuncionario.getColumnModel().getColumn(2).setResizable(false);
            tblFuncionario.getColumnModel().getColumn(3).setResizable(false);
        }
        tblFuncionario.getAccessibleContext().setAccessibleName("");

        jbDeletar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones32/Delete-32.png"))); // NOI18N
        jbDeletar.setText("Deletar");
        jbDeletar.setMaximumSize(new java.awt.Dimension(67, 67));
        jbDeletar.setPreferredSize(new java.awt.Dimension(65, 28));
        jbDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletarActionPerformed(evt);
            }
        });

        jbAtualizar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones32/Recurring Appointment-32.png"))); // NOI18N
        jbAtualizar.setText("Atualizar");
        jbAtualizar.setPreferredSize(new java.awt.Dimension(65, 28));
        jbAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Pesquisa:");

        btnPesquisar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones32/Find User Male-32.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setPreferredSize(new java.awt.Dimension(115, 28));
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        btnPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPesquisarKeyPressed(evt);
            }
        });

        txtPesquisa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyPressed(evt);
            }
        });

        jlpAlteracao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Manutenção De Usuários", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Arial", 1, 12))); // NOI18N
        jlpAlteracao.setAutoscrolls(true);

        btnCancelar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones32/Cancel-32.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setPreferredSize(new java.awt.Dimension(90, 28));
        btnCancelar.setRequestFocusEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        btnCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCancelarKeyPressed(evt);
            }
        });
        jlpAlteracao.add(btnCancelar);
        btnCancelar.setBounds(390, 280, 170, 28);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Codigo");
        jlpAlteracao.add(jLabel5);
        jLabel5.setBounds(170, 50, 40, 15);

        txtCodigo.setEditable(false);
        txtCodigo.setBackground(new java.awt.Color(222, 220, 220));
        txtCodigo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoKeyPressed(evt);
            }
        });
        jlpAlteracao.add(txtCodigo);
        txtCodigo.setBounds(220, 40, 330, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Senha");
        jlpAlteracao.add(jLabel8);
        jLabel8.setBounds(170, 150, 60, 15);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Tipo de usuário");
        jlpAlteracao.add(jLabel9);
        jLabel9.setBounds(90, 240, 110, 15);

        txtSenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        jlpAlteracao.add(txtSenha);
        txtSenha.setBounds(220, 140, 330, 30);

        jcbNomeTipo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcbNomeTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador", "Funcionario" }));
        jlpAlteracao.add(jcbNomeTipo);
        jcbNomeTipo.setBounds(220, 230, 120, 30);

        btnSalvarAlteracoes.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnSalvarAlteracoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones32/Salvar.png"))); // NOI18N
        btnSalvarAlteracoes.setText("Salvar Alterações");
        btnSalvarAlteracoes.setPreferredSize(new java.awt.Dimension(90, 28));
        btnSalvarAlteracoes.setRequestFocusEnabled(false);
        btnSalvarAlteracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarAlteracoesActionPerformed(evt);
            }
        });
        btnSalvarAlteracoes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSalvarAlteracoesKeyPressed(evt);
            }
        });
        jlpAlteracao.add(btnSalvarAlteracoes);
        btnSalvarAlteracoes.setBounds(150, 280, 190, 28);

        txtNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlpAlteracao.add(txtNome);
        txtNome.setBounds(220, 90, 330, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Nome");
        jlpAlteracao.add(jLabel10);
        jLabel10.setBounds(170, 100, 40, 15);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Confirmação de Senha");
        jlpAlteracao.add(jLabel11);
        jLabel11.setBounds(80, 200, 150, 15);

        txtConfirmacaoDeSenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlpAlteracao.add(txtConfirmacaoDeSenha);
        txtConfirmacaoDeSenha.setBounds(220, 190, 330, 30);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(226, 226, 226))
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlpAlteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                        .addComponent(jbAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jbDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jlpAlteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jLayeredPane3.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jbDeletar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jbAtualizar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(btnPesquisar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(txtPesquisa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jlpAlteracao, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jlpAlteracao.getAccessibleContext().setAccessibleName("Manutenção RH");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    DefaultTableModel dtm;
    int indiceLinhaSelecionada;

    public void limpar() {
        txtNome.setText("");
        txtCodigo.setText("");
        txtSenha.setText("");

    }

    private void salvar() throws Exception {
        GerenciadorArquivos.buscarArquivosUsuarios();
        try {
            for (int i = 0; i < arrayDeUsuarios.size(); i++) {
                if (arrayDeUsuarios.get(i).getNome().equals(txtNome.getText())
                        && arrayDeUsuarios.get(i).getCodigo() != Integer.parseInt(txtCodigo.getText())) {
                    throw new Exception("\n Nome já cadastrado!");
                } else if (!txtSenha.getText().equals(txtConfirmacaoDeSenha.getText())) {
                    throw new Exception("\n Confirmação de senha Inválida!");
                } else if (arrayDeUsuarios.get(i).getSenha().equals(txtSenha.getText()) && arrayDeUsuarios.get(i).getCodigo() == Integer.parseInt(txtCodigo.getText())) {

                    arrayDeUsuarios.get(i).setCodigo(Integer.parseInt(txtCodigo.getText()));
                    arrayDeUsuarios.get(i).setNome(txtNome.getText());
                    arrayDeUsuarios.get(i).setSenha(txtSenha.getText());
                    arrayDeUsuarios.get(i).setNomeTipo((String) jcbNomeTipo.getSelectedItem());

                    JOptionPane.showMessageDialog(this, "Aletração efetuada com sucesso!!", "Informativo", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            GerenciadorArquivos.salvarEAlterarUsuarios();
            GerenciadorArquivos.buscarArquivosUsuarios();
            this.inserirTodosFuncionariosNaTabela();
            this.limpar();
            jlpAlteracao.setVisible(false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), " ERRO ", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }

    public void inserirTodosFuncionariosNaTabela() {
        GerenciadorArquivos.buscarArquivosUsuarios();
        try {
            dtm = (DefaultTableModel) tblFuncionario.getModel();

            String[] linha = new String[4];
            dtm.setNumRows(0);
            GerenciadorArquivos.buscarArquivosUsuarios();

            for (int i = 0; i < arrayDeUsuarios.size(); i++) {
                linha[0] = String.valueOf(arrayDeUsuarios.get(i).getCodigo());
                linha[1] = arrayDeUsuarios.get(i).getNome();
                linha[2] = arrayDeUsuarios.get(i).getSenha();
                linha[3] = arrayDeUsuarios.get(i).getNomeTipo();
                dtm.addRow(linha);
            }//fecha for

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERRO " + e.getMessage());
            e.printStackTrace();
        }

    }

    private void buscar() {

        if (txtPesquisa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, " Infome um campo para pesquisa por favor! ", "  ALERTA ", JOptionPane.INFORMATION_MESSAGE);
            txtPesquisa.requestFocus();

        } else {

            String auxPesquisa = txtPesquisa.getText();

            dtm = (DefaultTableModel) tblFuncionario.getModel();
            dtm.setNumRows(0);
            String[] linha = new String[4];
            for (int i = 0; i < arrayDeUsuarios.size(); i++) {
                if (arrayDeUsuarios.get(i).getNome().equals(auxPesquisa)) {

                    linha[0] = String.valueOf(arrayDeUsuarios.get(i).getCodigo());
                    linha[1] = arrayDeUsuarios.get(i).getNome();
                    linha[2] = arrayDeUsuarios.get(i).getSenha();
                    linha[3] = arrayDeUsuarios.get(i).getNomeTipo();
                    dtm.addRow(linha);

                    txtCodigo.setText("" + arrayDeUsuarios.get(i).getCodigo());
                    txtNome.setText(arrayDeUsuarios.get(i).getNome());
                    txtSenha.setText(arrayDeUsuarios.get(i).getSenha());
                    jcbNomeTipo.setSelectedItem(arrayDeUsuarios.get(i).getNomeTipo().toString());
                }
            }
            if (dtm.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Funcionário Não Encontrado", "  ERRO  ", JOptionPane.ERROR_MESSAGE);
            }

        }
    }


    private void jbDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarActionPerformed

        GerenciadorArquivos.buscarArquivosUsuarios();
        try {
            String nome = (String) tblFuncionario.getValueAt(indiceLinhaSelecionada, 1).toString();
            String senha = (String) tblFuncionario.getValueAt(indiceLinhaSelecionada, 2).toString();
            if (!txtNome.getText().equals("")) {
                int aux = JOptionPane.showConfirmDialog(this, " Tem certeza de que deseja excluir este cadastro? ", "Exlcuir ", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

                if (JOptionPane.YES_OPTION == aux) {
                    for (int j = 0; j < arrayDeIdeia.size(); j++) {
                        if (arrayDeIdeia.get(j).getAuxFunconario().equals(nome)
                                && arrayDeUsuarios.get(j).getSenha().equals(senha)) {
                            JOptionPane.showMessageDialog(this, "Excluído com sucesso", "Exclusão de idéia", JOptionPane.INFORMATION_MESSAGE);
                            GerenciadorArquivos.deletarArquivoTodosArrays(nome, senha);
                            GerenciadorArquivos.buscarArquivosIdeia();
                        }
                    }
                    for (int i = 0; i < arrayDeUsuarios.size(); i++) {

                        if (arrayDeUsuarios.get(i).getNome().equals(nome)
                                && arrayDeUsuarios.get(i).getSenha().equals(senha)) {
                            JOptionPane.showMessageDialog(this, "Excluído com sucesso", "Exclusão de idéia", JOptionPane.INFORMATION_MESSAGE);
                            GerenciadorArquivos.deletarArquivoUsuarios(nome, senha);
                            GerenciadorArquivos.buscarArquivosUsuarios();
                            inserirTodosFuncionariosNaTabela();
                            this.limpar();
                        }
                    }

                } else {
                    inserirTodosFuncionariosNaTabela();
                    txtPesquisa.requestFocus();
                    aux = -1;
                    dispose();

                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "ERRO", "ERRO", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }

    }//GEN-LAST:event_jbDeletarActionPerformed

    private void jbAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarActionPerformed

        jlpAlteracao.setVisible(false);
        GerenciadorArquivos.buscarArquivosUsuarios();
        this.inserirTodosFuncionariosNaTabela();

    }//GEN-LAST:event_jbAtualizarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed

        if (txtPesquisa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite Seu Nome Por Favor!", " Informativo ", JOptionPane.INFORMATION_MESSAGE);
            txtPesquisa.requestFocus();
        } else {
            buscar();
            txtPesquisa.requestFocus();
        }

    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txtPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            buscar();
        }
    }//GEN-LAST:event_txtPesquisaKeyPressed

    private void btnPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnPesquisarKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            buscar();
        }
    }//GEN-LAST:event_btnPesquisarKeyPressed

    private void btnSalvarAlteracoesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSalvarAlteracoesKeyPressed

        try {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                salvar();
            } else if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
                salvar();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), " ERRO  ", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnSalvarAlteracoesKeyPressed

    private void btnSalvarAlteracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAlteracoesActionPerformed
        try {
            salvar();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "  ERRO  ", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnSalvarAlteracoesActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        jcbNomeTipo.requestFocus();
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void txtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtNome.requestFocus();
        }
    }//GEN-LAST:event_txtCodigoKeyPressed

    private void btnCancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCancelarKeyPressed
        try {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                limpar();
                txtPesquisa.requestFocus();
            } else if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
                limpar();
                txtPesquisa.requestFocus();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "  ERRO  ", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnCancelarKeyPressed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        limpar();
        txtPesquisa.requestFocus();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tblFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFuncionarioMouseClicked
        jlpAlteracao.setVisible(true);
        indiceLinhaSelecionada = tblFuncionario.getSelectedRow();
        txtPesquisa.setText((String) tblFuncionario.getValueAt(indiceLinhaSelecionada, 1).toString());

        buscar();

    }//GEN-LAST:event_tblFuncionarioMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvarAlteracoes;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAtualizar;
    private javax.swing.JButton jbDeletar;
    private javax.swing.JComboBox<String> jcbNomeTipo;
    private javax.swing.JLayeredPane jlpAlteracao;
    private javax.swing.JTable tblFuncionario;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JPasswordField txtConfirmacaoDeSenha;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables

}
