package view;

import javax.swing.JOptionPane;

/**
 * Classe responsavel por receber e instanciar as classes de cadastro de
 * ideias,alteração de ideias e cadastro de funcionarios onde estas instancias
 * são adicionadas a uma jlabel personalizada e setadas visivelmente para o
 * usuario.
 *
 * @author Huilton
 * @version 1.0
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    public Menu() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AreaDeTrabalho = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmAdministrador = new javax.swing.JMenu();
        jmiCadastroDeUsuarios = new javax.swing.JMenuItem();
        jmiManutencaoDeIdeia = new javax.swing.JMenuItem();
        jmiManutencaoDeUsuario = new javax.swing.JMenuItem();
        jmCadastros = new javax.swing.JMenu();
        jmiCadastrarIdeia = new javax.swing.JMenuItem();
        jmAlterarcoes = new javax.swing.JMenu();
        jmiAlterarIdeia = new javax.swing.JMenuItem();
        jmSair = new javax.swing.JMenu();
        jmiSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        AreaDeTrabalho.setBackground(new java.awt.Color(255, 255, 255));
        AreaDeTrabalho.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        AreaDeTrabalho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones32/Menu.png"))); // NOI18N
        AreaDeTrabalho.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bem vindo ao cadastro de idéias", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Arial", 1, 24))); // NOI18N

        jMenuBar1.setMaximumSize(new java.awt.Dimension(700, 900));

        jmAdministrador.setText("Menu Administrador");
        jmAdministrador.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jmiCadastroDeUsuarios.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jmiCadastroDeUsuarios.setText("Cadastrar Usuário");
        jmiCadastroDeUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastroDeUsuariosActionPerformed(evt);
            }
        });
        jmAdministrador.add(jmiCadastroDeUsuarios);

        jmiManutencaoDeIdeia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jmiManutencaoDeIdeia.setText("Manutenção De Idéia");
        jmiManutencaoDeIdeia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManutencaoDeIdeiaActionPerformed(evt);
            }
        });
        jmAdministrador.add(jmiManutencaoDeIdeia);

        jmiManutencaoDeUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jmiManutencaoDeUsuario.setText("Manutenção De Usuários");
        jmiManutencaoDeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManutencaoDeUsuarioActionPerformed(evt);
            }
        });
        jmAdministrador.add(jmiManutencaoDeUsuario);

        jMenuBar1.add(jmAdministrador);

        jmCadastros.setText("Cadastros");
        jmCadastros.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jmiCadastrarIdeia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jmiCadastrarIdeia.setText("Cadastrar Ideia");
        jmiCadastrarIdeia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastrarIdeiaActionPerformed(evt);
            }
        });
        jmCadastros.add(jmiCadastrarIdeia);

        jMenuBar1.add(jmCadastros);

        jmAlterarcoes.setText("Alteraçoes");
        jmAlterarcoes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jmiAlterarIdeia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jmiAlterarIdeia.setText(" Alteração E Exclusão de Idéia");
        jmiAlterarIdeia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAlterarIdeiaActionPerformed(evt);
            }
        });
        jmAlterarcoes.add(jmiAlterarIdeia);

        jMenuBar1.add(jmAlterarcoes);

        jmSair.setText("Sair");
        jmSair.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jmiSair.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jmiSair.setText("Sair");
        jmiSair.setFocusCycleRoot(true);
        jmiSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSairActionPerformed(evt);
            }
        });
        jmSair.add(jmiSair);

        jMenuBar1.add(jmSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AreaDeTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AreaDeTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public static String senhaLoginAux;
    public static String nomeLoginAux;
    public static int numeroTentativas;

    public void configurarCampos(int tipo) {
        if (tipo == 0) {//administrador
            jmiAlterarIdeia.setVisible(true);
            jmiCadastrarIdeia.setVisible(true);
            jmiCadastroDeUsuarios.setVisible(true);
            jmiSair.setVisible(true);
            jmiManutencaoDeUsuario.setVisible(true);
            jmAdministrador.setVisible(true);
            jmiManutencaoDeIdeia.setVisible(true);

        } else if (tipo == 1) {//funcionario

            jmiAlterarIdeia.setVisible(true);
            jmiCadastrarIdeia.setVisible(true);
            jmiCadastroDeUsuarios.setVisible(false);
            jmiSair.setVisible(true);
            jmiManutencaoDeUsuario.setVisible(false);
            jmAdministrador.setVisible(false);
            jmiManutencaoDeIdeia.setVisible(false);

        }
    }

    /**
     * Método do tipo void Monta o menu que é chamado no login para dar
     * permissões aos usuários
     *
     * @param tipo Paramentro do tipo byte. 0 - Administrador Permissão total no
     * sistema de Cadastrar, deletar e altera atributos(Caracteristicas) do
     * funcionário e do administrador | 1 - Funcionario Com Apenas permissões de
     * Cadastrar Idéia, Deletar Idéia e Alterar Idéia
     */
   

    private void jmiCadastrarIdeiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastrarIdeiaActionPerformed
        FrmiCadastrarIdeia cadastrarIdeia = new FrmiCadastrarIdeia();
        AreaDeTrabalho.add(cadastrarIdeia);
        cadastrarIdeia.setVisible(true);
    }//GEN-LAST:event_jmiCadastrarIdeiaActionPerformed

    private void jmiAlterarIdeiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAlterarIdeiaActionPerformed
        FrmiAlterarIdeia alterarIdeia = new FrmiAlterarIdeia();
        AreaDeTrabalho.add(alterarIdeia);
        alterarIdeia.setVisible(true);


    }//GEN-LAST:event_jmiAlterarIdeiaActionPerformed

    private void jmiCadastroDeUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastroDeUsuariosActionPerformed
        FrmiCadastroUsusarios cadastroDeFuncionarios = new FrmiCadastroUsusarios();
        AreaDeTrabalho.add(cadastroDeFuncionarios);
        cadastroDeFuncionarios.setVisible(true);
    }//GEN-LAST:event_jmiCadastroDeUsuariosActionPerformed

    private void jmiSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSairActionPerformed
        FrmLogin loginFuncionario = new FrmLogin();
        loginFuncionario.setVisible(true);
        dispose();
        senhaLoginAux = "";
        nomeLoginAux = "";
    }//GEN-LAST:event_jmiSairActionPerformed

    private void jmiManutencaoDeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManutencaoDeUsuarioActionPerformed
        FrmManutençãoDeUsuarios manutencaoAdministrador = new FrmManutençãoDeUsuarios();
        AreaDeTrabalho.add(manutencaoAdministrador);
        manutencaoAdministrador.setVisible(true);


    }//GEN-LAST:event_jmiManutencaoDeUsuarioActionPerformed

    private void jmiManutencaoDeIdeiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManutencaoDeIdeiaActionPerformed
        FrmManutençãoDeIdeias manutencaoIdeia = new FrmManutençãoDeIdeias();
        AreaDeTrabalho.add(manutencaoIdeia);
        manutencaoIdeia.setVisible(true);
    }//GEN-LAST:event_jmiManutencaoDeIdeiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AreaDeTrabalho;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmAdministrador;
    private javax.swing.JMenu jmAlterarcoes;
    private javax.swing.JMenu jmCadastros;
    private javax.swing.JMenu jmSair;
    private javax.swing.JMenuItem jmiAlterarIdeia;
    private javax.swing.JMenuItem jmiCadastrarIdeia;
    private javax.swing.JMenuItem jmiCadastroDeUsuarios;
    private javax.swing.JMenuItem jmiManutencaoDeIdeia;
    private javax.swing.JMenuItem jmiManutencaoDeUsuario;
    private javax.swing.JMenuItem jmiSair;
    // End of variables declaration//GEN-END:variables
}
